# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Distribute new debug application to firebase app distribution"
  lane :distribute_debug do
    if is_ci?
      sh("cd ../../ && $FLUTTER_HOME/bin/flutter build ios --no-codesign")
    else
      sh("cd ../../ && flutter build ios --no-codesign")
    end
  end
end
