# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distribute new debug application to firebase app distribution"
  lane :distribute_debug do
    sh("cd ../../ && flutter build apk --debug")
    firebase_app_distribution(
      app: "1:923170042883:android:ac46089ace0c303be70a36",
      testers: "tadashi.nemoto0713@gmail.com",
      apk_path: "../build/app/outputs/apk/debug/app-debug.apk",
      firebase_cli_token: ENV["FIREBASE_TOKEN"]
    )
  end
end
